import { NextResponse, after } from "next/server";
import { cookies } from "next/headers";
import { createClient } from "@/lib/supabase/server";
import { sendSignupNotification } from "@/lib/notifications/signup";

// Only OAuth (Google) sign-ins land here — email sign-ups go through /auth/confirm.
// A brand-new account was created moments ago; returning users are older.
const NEW_ACCOUNT_WINDOW_MS = 60_000;

function loginErrorUrl(origin: string, code: string, description?: string | null) {
  const params = new URLSearchParams({ error: code });
  if (description) params.set("error_description", description);
  return `${origin}/login?${params}`;
}

export async function GET(request: Request) {
  const { searchParams, origin } = new URL(request.url);
  const code = searchParams.get("code");
  const next = searchParams.get("next") ?? "/dashboard";

  if (code) {
    const hadCodeVerifier = (await cookies())
      .getAll()
      .some((c) => c.name.includes("code-verifier"));

    const supabase = await createClient();
    const { data, error } = await supabase.auth.exchangeCodeForSession(code);

    if (!error) {
      const user = data.user;
      if (user?.email && Date.now() - Date.parse(user.created_at) < NEW_ACCOUNT_WINDOW_MS) {
        // Username is generated by the handle_new_user() trigger
        const { data: profile } = await supabase
          .from("profiles")
          .select("username")
          .eq("id", user.id)
          .single();
        const email = user.email;
        after(() => sendSignupNotification(profile?.username ?? "(unknown)", email, "Google"));
      }

      const forwardedHost = request.headers.get("x-forwarded-host");
      const isLocalEnv = process.env.NODE_ENV === "development";

      if (isLocalEnv) {
        return NextResponse.redirect(`${origin}${next}`);
      } else if (forwardedHost) {
        return NextResponse.redirect(`https://${forwardedHost}${next}`);
      } else {
        return NextResponse.redirect(`${origin}${next}`);
      }
    }

    // Log the real cause server-side instead of leaving this a black box.
    // Never log the raw code — it's a single-use credential.
    console.error("[auth/callback] exchangeCodeForSession failed", {
      errorName: error.name,
      errorMessage: error.message,
      errorStatus: (error as { status?: number }).status,
      hadCodeVerifierCookie: hadCodeVerifier,
    });
    return NextResponse.redirect(loginErrorUrl(origin, "auth_callback_failed", error.message));
  }

  // Supabase's own /verify endpoint reports a specific reason (e.g. an
  // expired or already-used link) via `error`/`error_code` query params on
  // this same callback URL. Forward the code and description so /login can
  // show a matching banner with the details.
  const supabaseErrorCode = searchParams.get("error_code") ?? searchParams.get("error");
  if (supabaseErrorCode) {
    const errorDescription = searchParams.get("error_description");
    console.error("[auth/callback] Supabase reported a specific error", {
      errorCode: supabaseErrorCode,
      errorDescription,
    });
    return NextResponse.redirect(loginErrorUrl(origin, supabaseErrorCode, errorDescription));
  }

  console.error("[auth/callback] callback reached with no code and no error param", {
    fullUrl: request.url,
  });

  // Truly unexpected failure — redirect with the generic banner.
  return NextResponse.redirect(loginErrorUrl(origin, "auth_callback_failed"));
}
