export const REFERRER_LABELS: Record<string, string> = {
  "instagram.com": "Instagram",
  "l.instagram.com": "Instagram",
  "t.co": "Twitter / X",
  "x.com": "Twitter / X",
  "twitter.com": "Twitter / X",
  "l.tiktok.com": "TikTok",
  "tiktok.com": "TikTok",
  "vm.tiktok.com": "TikTok",
  "linktr.ee": "Linktree",
  "facebook.com": "Facebook",
  "m.facebook.com": "Facebook",
  "l.facebook.com": "Facebook",
  "lm.facebook.com": "Facebook",
  "youtube.com": "YouTube",
  "youtu.be": "YouTube",
  "m.youtube.com": "YouTube",
  "reddit.com": "Reddit",
  "old.reddit.com": "Reddit",
  "out.reddit.com": "Reddit",
  "snapchat.com": "Snapchat",
  "pinterest.com": "Pinterest",
  "pin.it": "Pinterest",
  "linkedin.com": "LinkedIn",
  "lnkd.in": "LinkedIn",
  "google.com": "Google",
  "search.google.com": "Google",
  "google.co.uk": "Google",
  "google.de": "Google",
  "google.fr": "Google",
  "google.ca": "Google",
  "google.com.au": "Google",
  "bing.com": "Bing",
  "yahoo.com": "Yahoo",
  "duckduckgo.com": "DuckDuckGo",
  "whatsapp.com": "WhatsApp",
  "wa.me": "WhatsApp",
  "telegram.org": "Telegram",
  "t.me": "Telegram",
  "discord.com": "Discord",
  "threads.net": "Threads",
  "beacons.ai": "Beacons",
  "bio.link": "Bio.link",
  "carrd.co": "Carrd",
  "later.com": "Later",
  "buffer.com": "Buffer",
  "hootsuite.com": "Hootsuite",
};

export function getReferrerLabel(host: string | null): string {
  if (!host) return "Direct";
  return REFERRER_LABELS[host] ?? host;
}
